name: Build and Organize

on:
  push:
    branches:
      - main

jobs:
  build-and-organize:
    runs-on: [self-hosted, runner2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 7.x
