name: Matrix Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet: [5.x, 6.x, 7.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Display OS and .NET Core Version
      run: |
        echo "Running on: ${{ matrix.os }}"
        echo "Using .NET Core version: ${{ matrix.dotnet }}"

    - name: Build and Test
      run: |
        dotnet build --configuration Release
        dotnet test
