name: Create Pull Request on Push to Dev

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev # The branch you want to create the pull request from
          title: "Automated Pull Request from Dev"
          body: "This pull request was automatically created when pushing to the dev branch."
          labels: "automated"
          base: main
          
